### ISSUE TITLE
It is necessary to use -pc and -d  flags to collect DR/Provider logs 

### ISSUE THREAD

**Issue by OdedViner** [red-hat-storage/odf-must-gather#133]
The scripts gather_dr_resources gather_odf_client  are not included in the "gather_main" script.
So for DR/Provider setup, we must use flags and not only basic command [oc adm must-gather --image=<>] 

https://github.com/red-hat-storage/odf-must-gather/blob/main/collection-scripts/gather_main
https://github.com/red-hat-storage/odf-must-gather/blob/c5787befcf522a23fe6d47d7add1e2a72d2cd932/collection-scripts/gather#L147
https://github.com/red-hat-storage/odf-must-gather/blob/c5787befcf522a23fe6d47d7add1e2a72d2cd932/collection-scripts/gather#L153

There are two options
1. Mention it in doc
2. Add [ "gather_dr_resources" and "gather_odf_client"] to "gather_main"
For DR we have a condition:
https://github.com/red-hat-storage/odf-must-gather/blob/main/collection-scripts/gather_dr_resources#L15

For Provider: 
We can create a condition and then we don't run the script on "non-provider" cluster.

**Comment by black-dragon74** [comment]
I think that is by design, right @yati1998 ?

**Comment by black-dragon74** [comment]
Mentioning it in doc should be considered anyways.

**Comment by yati1998** [comment]
> Mentioning it in doc should be considered anyways.

We can always work on improving documentation, will update the readme by end of this week with more details. no need to backport it, anyways we are a week away from GA, so adding these changes will be an issue. We will modify it in main and for coming releases, plus in the main documentation.
