### ISSUE TITLE
Support since and since-time to limit logs

### ISSUE THREAD

**Issue by black-dragon74** [red-hat-storage/odf-must-gather#139]
Abstract: OC Cli will create the MG container by supplying the ENV args `MUST_GATHER_SINCE` and `MUST_GATHER_SINCE_TIME`.

Adapt log collection to above params.

Ref: https://github.com/openshift/oc/commit/1fc5c7d79ff5c2fa19c35b7a004dc99eb3330806

**Comment by yati1998** [comment]
@black-dragon74 if it is resolved, Let's close the issue.
