### ISSUE TITLE
Ci fails with error docker/podman not found

### ISSUE THREAD

**Issue by yati1998** [red-hat-storage/odf-must-gather#46]
Since the ci doesn't automatically install docker/podman, the ci seems to fail. The ci is unable to build the image due to the absence of the platform. This needs to be fixed in openshift release repo(https://github.com/openshift/release) to build the image directly.

**Comment by black-dragon74** [comment]
Will be fixed with: https://github.com/openshift/release/pull/42408/

**Comment by black-dragon74** [comment]
This issue is solved. A side-effect of fixing this issue is tracked in #57 

Regards
